### ISSUE TITLE
ModuleNotFoundError: No module named 'ellipses'

### ISSUE THREAD

**Issue by guptavasu1213** [bdhammel/least-squares-ellipse-fitting#11]
I have cloned the repository and downloaded the pip package specified in the README, but I still end up getting this error.

**Comment by kip-hart** [comment]
The module name is "ellipse". If you change `import ellipses` to `import ellipse`, does that fix the issue? Below is the line with the module name.

https://github.com/bdhammel/least-squares-ellipse-fitting/blob/5441e5afc6b994a48b2dd9f4813cf69f4300c3e2/setup.py#L21

**Comment by bdhammel** [comment]
hm apologies, I've updated the readme. please let me know if this doesn't fix the issue

**Comment by bdhammel** [comment]
Closing as I assume this fixed the issue
