### ISSUE TITLE
Uncertainties calculation

### ISSUE THREAD

**Issue by stichou** [bdhammel/least-squares-ellipse-fitting#12]
Hello and thank you for your nice package.

Currently I use your package for fitting ellipses and it works perfect but I would like to know if there is way to output the uncertainties of the computed ellipse parameters ? If it's not implemented can you guide me to a paper explaining how to compute them for an ellipse fit.

Thank you in advance

**Comment by bdhammel** [comment]
Uncertainties cannot be done with this method, but this might help

https://github.com/bdhammel/least-squares-ellipse-fitting/issues/6#issuecomment-626175565
