### ISSUE TITLE
Documentation/ellipse definition sometimes confusing

### ISSUE THREAD

**Issue by b-neel** [bdhammel/least-squares-ellipse-fitting#13]
Hi,

Nice code, very helpful, thanks for making it public!

I was a little confused by one point in the code, but so far as I could spot, it's only a docstring (minor) issue:
- In ref (*) ([paper](../blob/master/media/WSCG98.pdf)) the ellipse is defined as *a x^2 + b x y + ...*, which are the coefficients returned in the corresponding attribute `ellipse.LsqEllipse.coefficients`.
- However, the docstring in that attribute `ellipse.LsqEllipse.coefficients` points to ref (**) ([MathWorld](https://mathworld.wolfram.com/Ellipse.html)), which defines the ellipse with additional factors: *a x^2 + **2** b x y + ...*, and is the source of my confusion.

In the method `as_parameters`, those factors are implemented where needed, but wouldn't it be clearer to:
- either modify the docstring where it needs to be modified,
- or incorporate the incriminated factors directly in the fitting routine (and harmonize the notation throughout the code)?

Happy holidays!

**Comment by bdhammel** [comment]
Thanks, should be solved in https://github.com/bdhammel/least-squares-ellipse-fitting/pull/19
