### ISSUE TITLE
Wrong angle calculation

### ISSUE THREAD

**Issue by bverlind1** [bdhammel/least-squares-ellipse-fitting#15]
Hello,

It seems that the angle calculation is not always correct.
I have this case and angle is  -0.13946737246282517
This seems the angle from Y axis instead of the X axis
![AngleEllipse](https://user-images.githubusercontent.com/87518398/125909678-fa11f65e-b3bb-4b88-9bc8-3afa5026952b.JPG)
[EllipseIn.txt](https://github.com/bdhammel/least-squares-ellipse-fitting/files/6828709/EllipseIn.txt)

**Comment by djibb** [comment]
hi, could you try it with this code : 
https://github.com/djibb/least-squares-ellipse-fitting

**Comment by bdhammel** [comment]
Thanks, should be solved in https://github.com/bdhammel/least-squares-ellipse-fitting/pull/19
