### ISSUE TITLE
fitting bug

### ISSUE THREAD

**Issue by GiganticRay** [bdhammel/least-squares-ellipse-fitting#17]
The error occurs when I call ```fit_obj.as_parameters``` if the given data failed to fit an ellipse. Since ```len(fit_ellipse_P.coefficients) = 0 ``` in this situation. As a user, I could only add a condition outside, But obviously, you guys could add this condition into the built-in code.

**Comment by bdhammel** [comment]
sorry I don't follow `len(fit_ellipse_P.coefficients) = 0` should never be zero. The code should error out completely before this. Can you give me a reproducible example?

**Comment by bdhammel** [comment]
Thanks, should be solved in https://github.com/bdhammel/least-squares-ellipse-fitting/pull/19
