### ISSUE TITLE
as_parameters() and compliance with Mathworld parameters definition

### ISSUE THREAD

**Issue by epascale** [bdhammel/least-squares-ellipse-fitting#23]
Hello, 
Many thanks for this great software that has been very useful to me. 

Upgrading from 2.0.1 to 2.2.1 I noticed that somehow the axis in which the parameters are returned are inverted. 
Digging a bit in the code I noticed that now width and height are inverted with respect to the definition of https://mathworld.wolfram.com/Ellipse.html, resulting in an ellipse with major axis aligned with the x-axis to have phi=90deg

Any reason to do that?

I would have thought the one below to be the the implementation complying with the Mathworld documentation.

Many thanks

-----------------------------------------

class myLsqEllipse(LsqEllipse):
    def as_parameters(self):
        """Returns the definition of the fitted ellipse as localized parameters

        Returns
        _______
        center : tuple
            (x0, y0)
        width : float
            Total length (diameter) of horizontal axis.
        height : float
            Total length (diameter) of vertical axis.
        phi : float
            The counterclockwise angle [radians] of rotation from the x-axis to the semimajor axis
        """

        # Eigenvectors are the coefficients of an ellipse in general form
        # the division by 2 is required to account for a slight difference in
        # the equations between (*) and (**)
        # a*x^2 +   b*x*y + c*y^2 +   d*x +   e*y + f = 0  (*)  Eqn 1
        # a*x^2 + 2*b*x*y + c*y^2 + 2*d*x + 2*f*y + g = 0  (**) Eqn 15
        # We'll use (**) to follow their documentation
        a = self.coefficients[0]
        b = self.coefficients[1] / 2.
        c = self.coefficients[2]
        d = self.coefficients[3] / 2.
        f = self.coefficients[4] / 2.
        g = self.coefficients[5]

        # Finding center of ellipse [eqn.19 and 20] from (**)
        x0 = (c*d - b*f) / (b**2 - a*c)
        y0 = (a*f - b*d) / (b**2 - a*c)
        center = (x0, y0)

        # Find the semi-axes lengths [eqn. 21 and 22] from (**)
        numerator = 2 * (a*f**2 + c*d**2 + g*b**2 - 2*b*d*f - a*c*g)
        denominator1 = (b**2 - a*c) * ( np.sqrt((a-c)**2+4*b**2) - (c+a))  # noqa: E201
        denominator2 = (b**2 - a*c) * (-np.sqrt((a-c)**2+4*b**2) - (c+a))
        width = np.sqrt(numerator / denominator1)
        height = np.sqrt(numerator / denominator2)

        # Angle of counterclockwise rotation of major-axis of ellipse to x-axis
        # [eqn. 23] from (**)
        # w/ trig identity eqn 9 form (***)
        if b == 0 and a < c:
            phi = 0.0
        elif b == 0 and a > c:
            phi = np.pi/2
        elif b != 0 and a < c:
            phi = 0.5 * np.arctan(2*b/(a-c))
        elif b != 0 and a > c:
            phi = 0.5 * (np.pi + np.arctan(2*b/(a-c)))
        elif a == c:
            phi = 0.0
        else:
            raise RuntimeError("Unreachable")

        return center, width, height, phi

**Comment by bdhammel** [comment]
Hi @epascale 
I did this to better match the matplotlib api, but the decision was mostly arbritrary...
(https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Ellipse.html)

sorry for the confusion this caused...
