### ISSUE TITLE
set condition for width and height of ellipse

### ISSUE THREAD

**Issue by kargarisaac** [bdhammel/least-squares-ellipse-fitting#3]
I have some points and want to fit an ellipse on them. But the fitted ellipse is big. is there any way to limit its size?

**Comment by bdhammel** [comment]
Unfortunately, I don't have time to look into this myself. But I believe you can set different constraint conditions (Eqn 2, Eqn 9, Eqn 18) in [Halir, Flusser] and done on line [60](https://github.com/bdhammel/least-squares-ellipse-fitting/blob/master/ellipses.py#L60) in my code

This paper talks about other constraints: http://cseweb.ucsd.edu/~mdailey/Face-Coord/ellipse-specific-fitting.pdf

So you might try exploring that; let me know if you find something that works!

**Comment by bdhammel** [comment]
Unfortunately, I don't have time to look into this myself. But I believe you can set different constraint conditions (Eqn 2, Eqn 9, Eqn 18) in [Halir, Flusser] and done on line [60](https://github.com/bdhammel/least-squares-ellipse-fitting/blob/master/ellipses.py#L60) in my code

This paper talks about other constraints: http://cseweb.ucsd.edu/~mdailey/Face-Coord/ellipse-specific-fitting.pdf

So you might try exploring that; let me know if you find something that works!
