### ISSUE TITLE
Code not on PyPI

### ISSUE THREAD

**Issue by kip-hart** [bdhammel/least-squares-ellipse-fitting#7]
Thank you for making this code available open source. It is very useful for my work.

Would you be willing to upload it to PyPI? This would be helpful for me because my package currently contains a copy of ``ellipses.py`` and I would rather import it.

I can help create the ``setup.py`` and ``MANIFEST.in`` files if you'd like.

**Comment by bdhammel** [comment]
I apologize for the very late reply. Uploading it to PyPI would be a good idea, I'll try to do that soon

**Comment by kip-hart** [comment]
No worries - offer still stands to help with the files.

**Comment by bdhammel** [comment]
Thanks for the offer. It will be good for me to go through the motions because I haven't actually done that before. Hopefully this week

**Comment by bdhammel** [comment]
https://pypi.org/project/lsq-ellipse/2.0.1/
